# Training configuration

model:
  freeze_backbone: True
  num_classes: 1

training:
  epochs: 12
  batch_size: 32
  learning_rate: 0.0001
  weight_decay: 0.0001
  early_stopping_patience: 5  # Optional: stop if no improvement for N epochs

paths:
  save_dir: "./outputs/models/resnet50_finetuned.pth"
  log_dir: "./outputs/logs"