model:
  freeze_backbone: True
  num_classes: 1

training:
  epochs: 12
  batch_size: 32
  learning_rate: 0.0001
  threshold: 0.5
  weight_decay: 0.0001
  max_norm: 1.0
  random_seed: 42
  early_stopping_patience: 5
  scheduler_factor: 0.5
  scheduler_patience: 3
  resume_training: False

amp:
  enabled: False

paths:
  save_dir: "../outputs/models/resnet50_finetuned.pth"
  checkpoint_dir: "../outputs/models/checkpoint.pth"
  log_dir: "../outputs/logs"
  checkpoint_folder: "../outputs/models/checkpoints/"
